-- liquibase formatted sql
--changeset rodionov:1-create-examples-and-flashcards-tables

CREATE TABLE my_app_schema.flashcards(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    folder_id BIGINT NOT NULL,
    phrase VARCHAR(255) NOT NULL,
    phrase_translation TEXT,
    target_language VARCHAR(50) NOT NULL,
    definition TEXT,
    CONSTRAINT fk_flashcards_user FOREIGN KEY (user_id) REFERENCES my_app_schema.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_flashcards_folder FOREIGN KEY (folder_id) REFERENCES my_app_schema.folders(id) ON DELETE CASCADE
);

CREATE TABLE my_app_schema.examples(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    example TEXT NOT NULL,
    ex_translation TEXT NOT NULL,
    without_target_words TEXT NOT NULL,
    CONSTRAINT fk_examples_card FOREIGN KEY (card_id) REFERENCES my_app_schema.flashcards(id) ON DELETE CASCADE
);

CREATE INDEX idx_flashcards_user_id ON my_app_schema.flashcards(user_id);
CREATE INDEX idx_flashcards_folder_id ON my_app_schema.flashcards(folder_id);
CREATE INDEX idx_examples_card_id ON my_app_schema.examples(card_id);
