-- liquibase formatted sql

--changeset rodionov:1-create-shelves-table
CREATE TABLE my_app_schema.shelves(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shelfName VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_shelves PRIMARY KEY (id)
);

ALTER TABLE my_app_schema.shelves
    ADD CONSTRAINT fk_shelves_user
    FOREIGN KEY (user_id)
    REFERENCES my_app_schema.users (id)
    ON DELETE CASCADE;

--changeset rodionov:2-create-books-table
CREATE TABLE my_app_schema.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    shelf_id BIGINT NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE my_app_schema.books
    ADD CONSTRAINT fk_books_shelf
    FOREIGN KEY (shelf_id)
    REFERENCES my_app_schema.shelves (id)
    ON DELETE CASCADE;
