-- liquibase formatted sql
--changeset rodionov:1-create-folders-table
CREATE TABLE my_app_schema.folders(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL,
name VARCHAR(500) NOT NULL,
CONSTRAINT fk_folders_user FOREIGN KEY (user_id) REFERENCES my_app_schema.users(id) ON DELETE CASCADE,
CONSTRAINT uk_folders_user_name UNIQUE (user_id, name)
);
CREATE INDEX idx_folders_user_id ON my_app_schema.folders(user_id);