-- liquibase formatted sql
--changeset rodionov:1-create-note-table
CREATE TABLE my_app_schema.notes(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
book_title VARCHAR(255) NOT NULL,
book_author VARCHAR(255),
selected_text TEXT NOT NULL,
note_text TEXT,
created_at TIMESTAMP WITH TIME ZONE NOT NULL,
cfi TEXT NOT NULL,
book_id BIGINT NOT NULL,
user_id BIGINT NOT NULL
)