spring:
  application:
    name: yourbookshelf

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  ai:
    google:
      genai:
        api-key: ${AI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash-lite
            temperature: 1

deepl:
    api-key: ${DEEPL_API_KEY}
    base-url: https://api-free.deepl.com

catbox:
  base-url: https://catbox.moe
  userhash: ${CATBOX_USERHASH}

